-- Seed: exercise database generated from docs/Uebungsdatenbank.xlsx
-- Do not edit by hand: change the xlsx and run supabase/seed/generate_exercises.py
-- Re-run safe: existing IDs are updated.
begin;
set constraints all deferred;
insert into public.exercises
  (id, name, base, pattern, primary_muscle, secondary, equipment, unilateral, tracking_type, level, alt1, alt2, video_url, hint, active, sort)
values
  ('BRU_BD_LH', 'Bankdrücken', 'Bankdrücken', 'Horizontal Drücken', 'Brust', array['Trizeps','Vordere Schulter']::text[], 'Langhantel', false, 'weight_reps', 'Einsteiger', 'BRU_BD_KH', 'BRU_BD_MP', null, 'Beispiel: Schulterblätter zurück und unten, Füße fest, Stange zur unteren Brust', true, 0),
  ('BRU_BD_KH', 'Kurzhantel-Bankdrücken', 'Bankdrücken', 'Horizontal Drücken', 'Brust', array['Trizeps','Vordere Schulter']::text[], 'Kurzhantel', false, 'weight_reps', 'Einsteiger', 'BRU_BD_LH', 'BRU_BP_MA', null, null, true, 1),
  ('BRU_BD_MP', 'Bankdrücken Multipresse', 'Bankdrücken', 'Horizontal Drücken', 'Brust', array['Trizeps','Vordere Schulter']::text[], 'Multipresse', false, 'weight_reps', 'Einsteiger', 'BRU_BD_LH', 'BRU_BD_KH', null, null, true, 2),
  ('BRU_SBD_LH', 'Schrägbankdrücken', 'Schrägbankdrücken', 'Horizontal Drücken', 'Brust', array['Vordere Schulter','Trizeps']::text[], 'Langhantel', false, 'weight_reps', 'Einsteiger', 'BRU_SBD_KH', 'BRU_SBD_MP', null, null, true, 3),
  ('BRU_SBD_KH', 'Kurzhantel-Schrägbankdrücken', 'Schrägbankdrücken', 'Horizontal Drücken', 'Brust', array['Vordere Schulter','Trizeps']::text[], 'Kurzhantel', false, 'weight_reps', 'Einsteiger', 'BRU_SBD_LH', 'BRU_SBD_MP', null, null, true, 4),
  ('BRU_SBD_MP', 'Schrägbankdrücken Multipresse', 'Schrägbankdrücken', 'Horizontal Drücken', 'Brust', array['Vordere Schulter','Trizeps']::text[], 'Multipresse', false, 'weight_reps', 'Einsteiger', 'BRU_SBD_KH', 'BRU_SBD_LH', null, null, true, 5),
  ('BRU_BP_MA', 'Brustpresse Maschine', 'Brustpresse', 'Horizontal Drücken', 'Brust', array['Trizeps','Vordere Schulter']::text[], 'Maschine', false, 'weight_reps', 'Einsteiger', 'BRU_BD_KH', 'BRU_LS', null, null, true, 6),
  ('BRU_DIP', 'Dips (Brust)', 'Dips', 'Horizontal Drücken', 'Brust', array['Trizeps','Vordere Schulter']::text[], 'Körpergewicht', false, 'bodyweight_plus', 'Fortgeschritten', 'BRU_DIP_ASS', 'BRU_BP_MA', null, null, true, 7),
  ('BRU_DIP_ASS', 'Dips mit Unterstützung', 'Dips', 'Horizontal Drücken', 'Brust', array['Trizeps','Vordere Schulter']::text[], 'Maschine', false, 'assisted', 'Einsteiger', 'BRU_DIP', 'BRU_BP_MA', null, null, true, 8),
  ('BRU_LS', 'Liegestütz', 'Liegestütz', 'Horizontal Drücken', 'Brust', array['Trizeps','Vordere Schulter','Bauch']::text[], 'Körpergewicht', false, 'bodyweight_reps', 'Einsteiger', 'BRU_BD_KH', 'BRU_BP_MA', null, null, true, 9),
  ('BRU_FLY_KA', 'Cable Fly', 'Fly', 'Isolation Oberkörper', 'Brust', array['Vordere Schulter']::text[], 'Kabel', false, 'weight_reps', 'Einsteiger', 'BRU_FLY_MA', 'BRU_FLY_KH', null, null, true, 10),
  ('BRU_FLY_MA', 'Butterfly Maschine', 'Fly', 'Isolation Oberkörper', 'Brust', array['Vordere Schulter']::text[], 'Maschine', false, 'weight_reps', 'Einsteiger', 'BRU_FLY_KA', 'BRU_FLY_KH', null, null, true, 11),
  ('BRU_FLY_KH', 'Kurzhantel-Fliegende', 'Fly', 'Isolation Oberkörper', 'Brust', array['Vordere Schulter']::text[], 'Kurzhantel', false, 'weight_reps', 'Einsteiger', 'BRU_FLY_KA', 'BRU_FLY_MA', null, null, true, 12),
  ('SCH_SD_LH', 'Schulterdrücken stehend (Military Press)', 'Schulterdrücken', 'Vertikal Drücken', 'Vordere Schulter', array['Seitliche Schulter','Trizeps']::text[], 'Langhantel', false, 'weight_reps', 'Fortgeschritten', 'SCH_SD_KH', 'SCH_SD_MA', null, null, true, 13),
  ('SCH_SD_KH', 'Kurzhantel-Schulterdrücken sitzend', 'Schulterdrücken', 'Vertikal Drücken', 'Vordere Schulter', array['Seitliche Schulter','Trizeps']::text[], 'Kurzhantel', false, 'weight_reps', 'Einsteiger', 'SCH_SD_MA', 'SCH_SD_LH', null, null, true, 14),
  ('SCH_SD_MA', 'Schulterpresse Maschine', 'Schulterdrücken', 'Vertikal Drücken', 'Vordere Schulter', array['Seitliche Schulter','Trizeps']::text[], 'Maschine', false, 'weight_reps', 'Einsteiger', 'SCH_SD_KH', 'SCH_SD_MP', null, null, true, 15),
  ('SCH_SD_MP', 'Schulterdrücken Multipresse', 'Schulterdrücken', 'Vertikal Drücken', 'Vordere Schulter', array['Seitliche Schulter','Trizeps']::text[], 'Multipresse', false, 'weight_reps', 'Einsteiger', 'SCH_SD_KH', 'SCH_SD_MA', null, null, true, 16),
  ('SCH_SH_KH', 'Seitheben Kurzhantel', 'Seitheben', 'Isolation Oberkörper', 'Seitliche Schulter', '{}'::text[], 'Kurzhantel', false, 'weight_reps', 'Einsteiger', 'SCH_SH_KA', 'SCH_SH_MA', null, null, true, 17),
  ('SCH_SH_KA', 'Seitheben Kabel einarmig', 'Seitheben', 'Isolation Oberkörper', 'Seitliche Schulter', '{}'::text[], 'Kabel', true, 'weight_reps', 'Einsteiger', 'SCH_SH_KH', 'SCH_SH_MA', null, null, true, 18),
  ('SCH_SH_MA', 'Seitheben Maschine', 'Seitheben', 'Isolation Oberkörper', 'Seitliche Schulter', '{}'::text[], 'Maschine', false, 'weight_reps', 'Einsteiger', 'SCH_SH_KH', 'SCH_SH_KA', null, null, true, 19),
  ('SCH_RF_MA', 'Reverse Fly Maschine', 'Reverse Fly', 'Isolation Oberkörper', 'Hintere Schulter', array['Oberer Rücken']::text[], 'Maschine', false, 'weight_reps', 'Einsteiger', 'SCH_RF_KA', 'SCH_FP_KA', null, null, true, 20),
  ('SCH_RF_KA', 'Reverse Fly Kabel', 'Reverse Fly', 'Isolation Oberkörper', 'Hintere Schulter', array['Oberer Rücken']::text[], 'Kabel', false, 'weight_reps', 'Einsteiger', 'SCH_RF_MA', 'SCH_FP_KA', null, null, true, 21),
  ('SCH_FP_KA', 'Face Pulls', 'Face Pulls', 'Horizontal Ziehen', 'Hintere Schulter', array['Oberer Rücken']::text[], 'Kabel', false, 'weight_reps', 'Einsteiger', 'SCH_RF_KA', 'SCH_RF_MA', null, null, true, 22),
  ('SCH_FH_KH', 'Frontheben Kurzhantel', 'Frontheben', 'Isolation Oberkörper', 'Vordere Schulter', '{}'::text[], 'Kurzhantel', false, 'weight_reps', 'Einsteiger', 'SCH_FH_KA', 'SCH_SD_KH', null, null, true, 23),
  ('SCH_FH_KA', 'Frontheben Kabel', 'Frontheben', 'Isolation Oberkörper', 'Vordere Schulter', '{}'::text[], 'Kabel', false, 'weight_reps', 'Einsteiger', 'SCH_FH_KH', 'SCH_SD_KH', null, null, true, 24),
  ('RUE_KZ', 'Klimmzug', 'Klimmzug', 'Vertikal Ziehen', 'Rücken (Lat)', array['Bizeps','Oberer Rücken']::text[], 'Körpergewicht', false, 'bodyweight_plus', 'Fortgeschritten', 'RUE_KZ_ASS', 'RUE_LZ_KA', null, null, true, 25),
  ('RUE_KZ_ASS', 'Klimmzug mit Unterstützung', 'Klimmzug', 'Vertikal Ziehen', 'Rücken (Lat)', array['Bizeps','Oberer Rücken']::text[], 'Maschine', false, 'assisted', 'Einsteiger', 'RUE_KZ', 'RUE_LZ_KA', null, null, true, 26),
  ('RUE_CU', 'Chin-Up (Untergriff)', 'Klimmzug', 'Vertikal Ziehen', 'Rücken (Lat)', array['Bizeps']::text[], 'Körpergewicht', false, 'bodyweight_plus', 'Fortgeschritten', 'RUE_KZ_ASS', 'RUE_LZ_UG', null, null, true, 27),
  ('RUE_LZ_KA', 'Latzug breit', 'Latzug', 'Vertikal Ziehen', 'Rücken (Lat)', array['Bizeps','Oberer Rücken']::text[], 'Kabel', false, 'weight_reps', 'Einsteiger', 'RUE_LZ_EN', 'RUE_KZ_ASS', null, null, true, 28),
  ('RUE_LZ_EN', 'Latzug eng', 'Latzug', 'Vertikal Ziehen', 'Rücken (Lat)', array['Bizeps']::text[], 'Kabel', false, 'weight_reps', 'Einsteiger', 'RUE_LZ_KA', 'RUE_LZ_EA', null, null, true, 29),
  ('RUE_LZ_UG', 'Latzug Untergriff', 'Latzug', 'Vertikal Ziehen', 'Rücken (Lat)', array['Bizeps']::text[], 'Kabel', false, 'weight_reps', 'Einsteiger', 'RUE_LZ_EN', 'RUE_LZ_KA', null, null, true, 30),
  ('RUE_LZ_EA', 'Latzug einarmig', 'Latzug', 'Vertikal Ziehen', 'Rücken (Lat)', array['Bizeps']::text[], 'Kabel', true, 'weight_reps', 'Einsteiger', 'RUE_LZ_EN', 'RUE_LZ_KA', null, null, true, 31),
  ('RUE_PD_KA', 'Lat-Überzüge Kabel (Pullover)', 'Lat-Überzüge', 'Isolation Oberkörper', 'Rücken (Lat)', '{}'::text[], 'Kabel', false, 'weight_reps', 'Einsteiger', 'RUE_LZ_EN', 'RUE_LZ_KA', null, null, true, 32),
  ('RUE_RU_LH', 'Langhantelrudern vorgebeugt', 'Rudern', 'Horizontal Ziehen', 'Oberer Rücken', array['Rücken (Lat)','Hintere Schulter','Bizeps']::text[], 'Langhantel', false, 'weight_reps', 'Fortgeschritten', 'RUE_RU_KH', 'RUE_RU_MA', null, null, true, 33),
  ('RUE_RU_KH', 'Kurzhantelrudern einarmig', 'Rudern', 'Horizontal Ziehen', 'Rücken (Lat)', array['Oberer Rücken','Bizeps']::text[], 'Kurzhantel', true, 'weight_reps', 'Einsteiger', 'RUE_RU_KA', 'RUE_RU_MA', null, null, true, 34),
  ('RUE_RU_KA', 'Kabelrudern sitzend', 'Rudern', 'Horizontal Ziehen', 'Oberer Rücken', array['Rücken (Lat)','Bizeps']::text[], 'Kabel', false, 'weight_reps', 'Einsteiger', 'RUE_RU_MA', 'RUE_RU_KH', null, null, true, 35),
  ('RUE_RU_MA', 'Rudermaschine (brustgestützt)', 'Rudern', 'Horizontal Ziehen', 'Oberer Rücken', array['Rücken (Lat)','Hintere Schulter']::text[], 'Maschine', false, 'weight_reps', 'Einsteiger', 'RUE_RU_KA', 'RUE_RU_TB', null, null, true, 36),
  ('RUE_RU_TB', 'T-Bar-Rudern', 'Rudern', 'Horizontal Ziehen', 'Oberer Rücken', array['Rücken (Lat)','Bizeps']::text[], 'Maschine', false, 'weight_reps', 'Fortgeschritten', 'RUE_RU_MA', 'RUE_RU_LH', null, null, true, 37),
  ('RUE_RU_KHB', 'Kurzhantelrudern auf Schrägbank', 'Rudern', 'Horizontal Ziehen', 'Oberer Rücken', array['Hintere Schulter']::text[], 'Kurzhantel', false, 'weight_reps', 'Einsteiger', 'RUE_RU_MA', 'RUE_RU_KA', null, null, true, 38),
  ('RUE_SHR_KH', 'Shrugs Kurzhantel', 'Shrugs', 'Isolation Oberkörper', 'Oberer Rücken', array['Unterarme']::text[], 'Kurzhantel', false, 'weight_reps', 'Einsteiger', 'RUE_SHR_LH', 'RUE_SHR_MA', null, null, true, 39),
  ('RUE_SHR_LH', 'Shrugs Langhantel', 'Shrugs', 'Isolation Oberkörper', 'Oberer Rücken', array['Unterarme']::text[], 'Langhantel', false, 'weight_reps', 'Einsteiger', 'RUE_SHR_KH', 'RUE_SHR_MA', null, null, true, 40),
  ('RUE_SHR_MA', 'Shrugs Maschine', 'Shrugs', 'Isolation Oberkörper', 'Oberer Rücken', '{}'::text[], 'Maschine', false, 'weight_reps', 'Einsteiger', 'RUE_SHR_KH', 'RUE_SHR_LH', null, null, true, 41),
  ('RUE_HE', 'Hyperextensions', 'Hyperextensions', 'Hüftstreckung', 'Unterer Rücken', array['Gesäß','Beinbeuger']::text[], 'Körpergewicht', false, 'bodyweight_plus', 'Einsteiger', 'BEI_RDL_LH', 'BEI_GM', null, null, true, 42),
  ('BIZ_CU_LH', 'Langhantel-Curls', 'Curls', 'Isolation Oberkörper', 'Bizeps', array['Unterarme']::text[], 'Langhantel', false, 'weight_reps', 'Einsteiger', 'BIZ_CU_SZ', 'BIZ_CU_KH', null, null, true, 43),
  ('BIZ_CU_SZ', 'SZ-Curls', 'Curls', 'Isolation Oberkörper', 'Bizeps', array['Unterarme']::text[], 'SZ-Stange', false, 'weight_reps', 'Einsteiger', 'BIZ_CU_LH', 'BIZ_CU_KH', null, null, true, 44),
  ('BIZ_CU_KH', 'Kurzhantel-Curls', 'Curls', 'Isolation Oberkörper', 'Bizeps', array['Unterarme']::text[], 'Kurzhantel', false, 'weight_reps', 'Einsteiger', 'BIZ_CU_SZ', 'BIZ_CU_KA', null, null, true, 45),
  ('BIZ_HC_KH', 'Hammercurls', 'Hammercurls', 'Isolation Oberkörper', 'Bizeps', array['Unterarme']::text[], 'Kurzhantel', false, 'weight_reps', 'Einsteiger', 'BIZ_HC_KA', 'BIZ_CU_KH', null, null, true, 46),
  ('BIZ_HC_KA', 'Hammercurls Kabel (Seil)', 'Hammercurls', 'Isolation Oberkörper', 'Bizeps', array['Unterarme']::text[], 'Kabel', false, 'weight_reps', 'Einsteiger', 'BIZ_HC_KH', 'BIZ_CU_KA', null, null, true, 47),
  ('BIZ_CU_KA', 'Kabelcurls', 'Curls', 'Isolation Oberkörper', 'Bizeps', '{}'::text[], 'Kabel', false, 'weight_reps', 'Einsteiger', 'BIZ_CU_KH', 'BIZ_CU_SZ', null, null, true, 48),
  ('BIZ_SC', 'Scottcurls (Preacher)', 'Scottcurls', 'Isolation Oberkörper', 'Bizeps', '{}'::text[], 'SZ-Stange', false, 'weight_reps', 'Einsteiger', 'BIZ_SC_MA', 'BIZ_CU_SZ', null, null, true, 49),
  ('BIZ_SC_MA', 'Bizepsmaschine', 'Scottcurls', 'Isolation Oberkörper', 'Bizeps', '{}'::text[], 'Maschine', false, 'weight_reps', 'Einsteiger', 'BIZ_SC', 'BIZ_CU_KA', null, null, true, 50),
  ('BIZ_IC', 'Schrägbank-Curls (Incline)', 'Curls', 'Isolation Oberkörper', 'Bizeps', '{}'::text[], 'Kurzhantel', false, 'weight_reps', 'Fortgeschritten', 'BIZ_CU_KH', 'BIZ_CU_KA', null, null, true, 51),
  ('TRI_PD_SE', 'Trizepsdrücken Seil', 'Trizepsdrücken', 'Isolation Oberkörper', 'Trizeps', '{}'::text[], 'Kabel', false, 'weight_reps', 'Einsteiger', 'TRI_PD_ST', 'TRI_UK_KA', null, null, true, 52),
  ('TRI_PD_ST', 'Trizepsdrücken Stange', 'Trizepsdrücken', 'Isolation Oberkörper', 'Trizeps', '{}'::text[], 'Kabel', false, 'weight_reps', 'Einsteiger', 'TRI_PD_SE', 'TRI_UK_KA', null, null, true, 53),
  ('TRI_UK_KA', 'Überkopf-Trizepsstrecken Kabel', 'Überkopf-Trizeps', 'Isolation Oberkörper', 'Trizeps', '{}'::text[], 'Kabel', false, 'weight_reps', 'Einsteiger', 'TRI_UK_KH', 'TRI_SC', null, null, true, 54),
  ('TRI_UK_KH', 'Überkopf-Trizepsstrecken Kurzhantel', 'Überkopf-Trizeps', 'Isolation Oberkörper', 'Trizeps', '{}'::text[], 'Kurzhantel', false, 'weight_reps', 'Einsteiger', 'TRI_UK_KA', 'TRI_SC', null, null, true, 55),
  ('TRI_SC', 'French Press / Skullcrusher', 'Skullcrusher', 'Isolation Oberkörper', 'Trizeps', '{}'::text[], 'SZ-Stange', false, 'weight_reps', 'Einsteiger', 'TRI_UK_KA', 'TRI_PD_SE', null, null, true, 56),
  ('TRI_BDE', 'Enges Bankdrücken', 'Enges Bankdrücken', 'Horizontal Drücken', 'Trizeps', array['Brust','Vordere Schulter']::text[], 'Langhantel', false, 'weight_reps', 'Fortgeschritten', 'TRI_DIP_MA', 'TRI_SC', null, null, true, 57),
  ('TRI_DIP_MA', 'Dipmaschine (Trizeps)', 'Dips', 'Isolation Oberkörper', 'Trizeps', array['Brust']::text[], 'Maschine', false, 'weight_reps', 'Einsteiger', 'TRI_PD_ST', 'TRI_BDE', null, null, true, 58),
  ('UNT_RC', 'Reverse Curls', 'Unterarm', 'Isolation Oberkörper', 'Unterarme', array['Bizeps']::text[], 'SZ-Stange', false, 'weight_reps', 'Einsteiger', 'UNT_WC', 'BIZ_HC_KH', null, null, true, 59),
  ('UNT_WC', 'Handgelenk-Curls', 'Unterarm', 'Isolation Oberkörper', 'Unterarme', '{}'::text[], 'Kurzhantel', false, 'weight_reps', 'Einsteiger', 'UNT_RC', 'CAR_FW', null, null, true, 60),
  ('BEI_KB_LH', 'Kniebeuge (Back Squat)', 'Kniebeuge', 'Kniebeuge', 'Quadrizeps', array['Gesäß','Adduktoren','Unterer Rücken']::text[], 'Langhantel', false, 'weight_reps', 'Fortgeschritten', 'BEI_KB_MP', 'BEI_HS', null, null, true, 61),
  ('BEI_FS_LH', 'Frontkniebeuge', 'Kniebeuge', 'Kniebeuge', 'Quadrizeps', array['Gesäß','Bauch']::text[], 'Langhantel', false, 'weight_reps', 'Fortgeschritten', 'BEI_KB_LH', 'BEI_GS_KH', null, null, true, 62),
  ('BEI_KB_MP', 'Kniebeuge Multipresse', 'Kniebeuge', 'Kniebeuge', 'Quadrizeps', array['Gesäß']::text[], 'Multipresse', false, 'weight_reps', 'Einsteiger', 'BEI_HS', 'BEI_BP', null, null, true, 63),
  ('BEI_GS_KH', 'Goblet Squat', 'Kniebeuge', 'Kniebeuge', 'Quadrizeps', array['Gesäß','Bauch']::text[], 'Kurzhantel', false, 'weight_reps', 'Einsteiger', 'BEI_BP', 'BEI_KB_MP', null, null, true, 64),
  ('BEI_HS', 'Hackenschmidt', 'Kniebeuge', 'Kniebeuge', 'Quadrizeps', array['Gesäß']::text[], 'Maschine', false, 'weight_reps', 'Einsteiger', 'BEI_BP', 'BEI_KB_MP', null, null, true, 65),
  ('BEI_PS', 'Pendulum Squat', 'Kniebeuge', 'Kniebeuge', 'Quadrizeps', array['Gesäß']::text[], 'Maschine', false, 'weight_reps', 'Einsteiger', 'BEI_HS', 'BEI_BP', null, null, true, 66),
  ('BEI_BP', 'Beinpresse', 'Beinpresse', 'Kniebeuge', 'Quadrizeps', array['Gesäß','Adduktoren']::text[], 'Maschine', false, 'weight_reps', 'Einsteiger', 'BEI_HS', 'BEI_KB_MP', null, null, true, 67),
  ('BEI_BS', 'Beinstrecker', 'Beinstrecker', 'Isolation Unterkörper', 'Quadrizeps', '{}'::text[], 'Maschine', false, 'weight_reps', 'Einsteiger', 'BEI_BS_EA', 'BEI_GS_KH', null, null, true, 68),
  ('BEI_BS_EA', 'Beinstrecker einbeinig', 'Beinstrecker', 'Isolation Unterkörper', 'Quadrizeps', '{}'::text[], 'Maschine', true, 'weight_reps', 'Einsteiger', 'BEI_BS', 'BEI_GS_KH', null, null, true, 69),
  ('BEI_BU', 'Bulgarian Split Squat', 'Split Squat', 'Ausfallschritt', 'Quadrizeps', array['Gesäß','Adduktoren']::text[], 'Kurzhantel', true, 'weight_reps', 'Fortgeschritten', 'BEI_AS_KH', 'BEI_SPS_MP', null, null, true, 70),
  ('BEI_SPS_MP', 'Split Squat Multipresse', 'Split Squat', 'Ausfallschritt', 'Quadrizeps', array['Gesäß']::text[], 'Multipresse', true, 'weight_reps', 'Einsteiger', 'BEI_BU', 'BEI_AS_KH', null, null, true, 71),
  ('BEI_AS_KH', 'Ausfallschritte (Walking Lunges)', 'Ausfallschritt', 'Ausfallschritt', 'Quadrizeps', array['Gesäß','Adduktoren']::text[], 'Kurzhantel', true, 'weight_reps', 'Einsteiger', 'BEI_BU', 'BEI_STU', null, null, true, 72),
  ('BEI_STU', 'Step-Ups', 'Ausfallschritt', 'Ausfallschritt', 'Quadrizeps', array['Gesäß']::text[], 'Kurzhantel', true, 'weight_reps', 'Einsteiger', 'BEI_AS_KH', 'BEI_BU', null, null, true, 73),
  ('BEI_KH_LH', 'Kreuzheben', 'Kreuzheben', 'Hüftstreckung', 'Beinbeuger', array['Gesäß','Unterer Rücken','Oberer Rücken','Unterarme']::text[], 'Langhantel', false, 'weight_reps', 'Fortgeschritten', 'BEI_TB', 'BEI_RDL_LH', null, null, true, 74),
  ('BEI_TB', 'Trap-Bar-Kreuzheben', 'Kreuzheben', 'Hüftstreckung', 'Quadrizeps', array['Gesäß','Beinbeuger','Oberer Rücken']::text[], 'Langhantel', false, 'weight_reps', 'Einsteiger', 'BEI_KH_LH', 'BEI_RDL_LH', null, null, true, 75),
  ('BEI_RDL_LH', 'Rumänisches Kreuzheben', 'Rumänisches Kreuzheben', 'Hüftstreckung', 'Beinbeuger', array['Gesäß','Unterer Rücken']::text[], 'Langhantel', false, 'weight_reps', 'Einsteiger', 'BEI_RDL_KH', 'BEI_BC_LI', null, null, true, 76),
  ('BEI_RDL_KH', 'Rumänisches Kreuzheben Kurzhantel', 'Rumänisches Kreuzheben', 'Hüftstreckung', 'Beinbeuger', array['Gesäß','Unterer Rücken']::text[], 'Kurzhantel', false, 'weight_reps', 'Einsteiger', 'BEI_RDL_LH', 'BEI_BC_LI', null, null, true, 77),
  ('BEI_RDL_EB', 'Einbeiniges Rumänisches Kreuzheben', 'Rumänisches Kreuzheben', 'Hüftstreckung', 'Beinbeuger', array['Gesäß']::text[], 'Kurzhantel', true, 'weight_reps', 'Fortgeschritten', 'BEI_RDL_KH', 'BEI_BC_SI', null, null, true, 78),
  ('BEI_GM', 'Good Mornings', 'Good Mornings', 'Hüftstreckung', 'Beinbeuger', array['Unterer Rücken','Gesäß']::text[], 'Langhantel', false, 'weight_reps', 'Fortgeschritten', 'BEI_RDL_LH', 'RUE_HE', null, null, true, 79),
  ('BEI_BC_LI', 'Beinbeuger liegend', 'Beinbeuger', 'Isolation Unterkörper', 'Beinbeuger', array['Waden']::text[], 'Maschine', false, 'weight_reps', 'Einsteiger', 'BEI_BC_SI', 'BEI_RDL_KH', null, null, true, 80),
  ('BEI_BC_SI', 'Beinbeuger sitzend', 'Beinbeuger', 'Isolation Unterkörper', 'Beinbeuger', '{}'::text[], 'Maschine', false, 'weight_reps', 'Einsteiger', 'BEI_BC_LI', 'BEI_RDL_KH', null, null, true, 81),
  ('BEI_NC', 'Nordic Curls', 'Beinbeuger', 'Isolation Unterkörper', 'Beinbeuger', '{}'::text[], 'Körpergewicht', false, 'bodyweight_reps', 'Fortgeschritten', 'BEI_BC_LI', 'BEI_BC_SI', null, null, true, 82),
  ('GES_HT_LH', 'Hip Thrust', 'Hip Thrust', 'Hüftstreckung', 'Gesäß', array['Beinbeuger']::text[], 'Langhantel', false, 'weight_reps', 'Einsteiger', 'GES_HT_MA', 'GES_GB', null, null, true, 83),
  ('GES_HT_MA', 'Hip Thrust Maschine', 'Hip Thrust', 'Hüftstreckung', 'Gesäß', array['Beinbeuger']::text[], 'Maschine', false, 'weight_reps', 'Einsteiger', 'GES_HT_LH', 'GES_GB', null, null, true, 84),
  ('GES_GB', 'Glute Bridge', 'Hip Thrust', 'Hüftstreckung', 'Gesäß', array['Beinbeuger']::text[], 'Körpergewicht', false, 'bodyweight_plus', 'Einsteiger', 'GES_HT_LH', 'GES_HT_MA', null, null, true, 85),
  ('GES_KB_KA', 'Kickbacks Kabel', 'Gesäß-Isolation', 'Isolation Unterkörper', 'Gesäß', '{}'::text[], 'Kabel', true, 'weight_reps', 'Einsteiger', 'GES_ABD', 'GES_HT_MA', null, null, true, 86),
  ('GES_ABD', 'Abduktoren Maschine', 'Abduktoren', 'Isolation Unterkörper', 'Gesäß', '{}'::text[], 'Maschine', false, 'weight_reps', 'Einsteiger', 'GES_KB_KA', 'GES_HT_LH', null, null, true, 87),
  ('GES_KS', 'Kettlebell Swing', 'Kettlebell Swing', 'Hüftstreckung', 'Gesäß', array['Beinbeuger','Unterer Rücken']::text[], 'Kettlebell', false, 'weight_reps', 'Fortgeschritten', 'GES_HT_LH', 'BEI_RDL_KH', null, null, true, 88),
  ('ADD_MA', 'Adduktoren Maschine', 'Adduktoren', 'Isolation Unterkörper', 'Adduktoren', '{}'::text[], 'Maschine', false, 'weight_reps', 'Einsteiger', 'BEI_GS_KH', 'BEI_BU', null, null, true, 89),
  ('WAD_ST_MA', 'Wadenheben stehend', 'Wadenheben', 'Isolation Unterkörper', 'Waden', '{}'::text[], 'Maschine', false, 'weight_reps', 'Einsteiger', 'WAD_BP', 'WAD_SI', null, null, true, 90),
  ('WAD_SI', 'Wadenheben sitzend', 'Wadenheben', 'Isolation Unterkörper', 'Waden', '{}'::text[], 'Maschine', false, 'weight_reps', 'Einsteiger', 'WAD_ST_MA', 'WAD_BP', null, null, true, 91),
  ('WAD_BP', 'Wadenheben Beinpresse', 'Wadenheben', 'Isolation Unterkörper', 'Waden', '{}'::text[], 'Maschine', false, 'weight_reps', 'Einsteiger', 'WAD_ST_MA', 'WAD_SI', null, null, true, 92),
  ('BAU_CR_KA', 'Kabel-Crunch', 'Crunch', 'Rumpf', 'Bauch', '{}'::text[], 'Kabel', false, 'weight_reps', 'Einsteiger', 'BAU_CR_MA', 'BAU_CR', null, null, true, 93),
  ('BAU_CR_MA', 'Bauchmaschine', 'Crunch', 'Rumpf', 'Bauch', '{}'::text[], 'Maschine', false, 'weight_reps', 'Einsteiger', 'BAU_CR_KA', 'BAU_CR', null, null, true, 94),
  ('BAU_CR', 'Crunch', 'Crunch', 'Rumpf', 'Bauch', '{}'::text[], 'Körpergewicht', false, 'bodyweight_reps', 'Einsteiger', 'BAU_CR_KA', 'BAU_CR_MA', null, null, true, 95),
  ('BAU_BH_H', 'Beinheben hängend', 'Beinheben', 'Rumpf', 'Bauch', array['Unterarme']::text[], 'Körpergewicht', false, 'bodyweight_reps', 'Fortgeschritten', 'BAU_BH_S', 'BAU_CR_KA', null, null, true, 96),
  ('BAU_BH_S', 'Beinheben am Dipständer (Captain''s Chair)', 'Beinheben', 'Rumpf', 'Bauch', '{}'::text[], 'Körpergewicht', false, 'bodyweight_reps', 'Einsteiger', 'BAU_BH_H', 'BAU_CR', null, null, true, 97),
  ('BAU_PL', 'Plank', 'Plank', 'Rumpf', 'Bauch', array['Vordere Schulter']::text[], 'Körpergewicht', false, 'time', 'Einsteiger', 'BAU_SPL', 'BAU_AW', null, null, true, 98),
  ('BAU_SPL', 'Seitstütz', 'Plank', 'Rumpf', 'Bauch', '{}'::text[], 'Körpergewicht', true, 'time', 'Einsteiger', 'BAU_PL', 'BAU_PA', null, null, true, 99),
  ('BAU_AW', 'Ab Wheel Rollout', 'Rollout', 'Rumpf', 'Bauch', array['Rücken (Lat)']::text[], 'Körpergewicht', false, 'bodyweight_reps', 'Fortgeschritten', 'BAU_PL', 'BAU_CR_KA', null, null, true, 100),
  ('BAU_PA', 'Pallof Press', 'Anti-Rotation', 'Rumpf', 'Bauch', '{}'::text[], 'Kabel', true, 'weight_reps', 'Einsteiger', 'BAU_SPL', 'BAU_PL', null, null, true, 101),
  ('BAU_DB', 'Dead Bug', 'Dead Bug', 'Rumpf', 'Bauch', '{}'::text[], 'Körpergewicht', false, 'bodyweight_reps', 'Einsteiger', 'BAU_PL', 'BAU_CR', null, null, true, 102),
  ('CAR_FW', 'Farmer''s Walk', 'Tragen', 'Tragen', 'Unterarme', array['Oberer Rücken','Bauch']::text[], 'Kurzhantel', false, 'distance', 'Einsteiger', 'UNT_WC', 'RUE_SHR_KH', null, null, true, 103),
  ('CAR_SW', 'Suitcase Carry', 'Tragen', 'Tragen', 'Bauch', array['Unterarme']::text[], 'Kurzhantel', true, 'distance', 'Einsteiger', 'CAR_FW', 'BAU_SPL', null, null, true, 104)
on conflict (id) do update set
  name = excluded.name, base = excluded.base, pattern = excluded.pattern,
  primary_muscle = excluded.primary_muscle, secondary = excluded.secondary,
  equipment = excluded.equipment, unilateral = excluded.unilateral,
  tracking_type = excluded.tracking_type, level = excluded.level,
  alt1 = excluded.alt1, alt2 = excluded.alt2, video_url = excluded.video_url,
  hint = excluded.hint, active = excluded.active, sort = excluded.sort;
commit;
